#spring.jpa:
#  database: postgresql
#  hibernate.dialect: org.hibernate.dilect.PostgreSQLDialect
#  hibernate.ddl-auto: update
#  properties.hibernate.format_sql: true


spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  logging:
    level:
      org.hibernate.SQL: debug