
#spring:
#  datasource:
#    hikari:
#      maximum-pool-size: 4
#      driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password:
#
#  jpa:
#    database: postgresql
#    hibernate:
#      ddl-auto: update
#      dialect: org.hibernate.dilect.PostgreSQLDialect
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true



spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    host: 15.164.166.12
    port: 6379


jwt:
  secret-key: "study.text-sns-application-2023.secret_key"
  #30 days
  token.expired-time-ms: 2592000000

#  logging:
#    level:
#      org.hibernate.SQL: debug
